### ISSUE TITLE
EntityPick is vertically inverted

### ISSUE THREAD

**Issue by blitzcoder** [angros47/OpenB3D#7]
It seems when doing EntityPick, the projection is vertically inverted.

**Comment by angros47** [comment]
I tried to run a simple test, and EntityPick worked as expected to me.

Are you sure you aren't talking about CameraPick, instead? In
CameraPick indeed the projection is vertically inverted (at least
compared to Blitz3D): it is also stated in the documentation:

"Return the entity that is at the coordinates x and y of the viewport
(be careful: coordinates 0,0 point to the bottom left angle of the
viewport)"


If CameraPick works as expected, in your version, and EntityPick
inverts the coordinates, it is maybe possible that you have inverted
the sign of the value returned by PickedY() somewhere?


Il giorno mer, 19/04/2023 alle 03.06 -0700, RonTek ha scritto:

**Comment by blitzcoder** [comment]
Yes, it is CameraPick with EntityPick. It does solve the issue when screenheight - y is used, thanks.
