### ISSUE TITLE
SpriteViewMode 3 and 4 Camera Issues

### ISSUE THREAD

**Issue by blitzcoder** [angros47/OpenB3D#8]
I noticed Mode 3 does not always face the camera, but it does roll with it.

Same with Mode 4 where it also rolls with the camera, but when slowly changing the pitch from front to the top, it spins and vanishes instead of seeing the top of the sprite.

I have tested this with the SpriteViewMode example similar setup to Blitz3D (see screenshot below).

Also, both modes 3 and 4 flips the sprite backwards instead of facing the camera by default when changing from mode 1 and 2.
I have to turn the pivot around to re-orient and test both of these modes.

I did check the `Camera::UpdateSprite` function which seems to be related to this issue and same as the version I'm using. I also have the same result testing it in OpenB3D BlitzMax.

Mode3 (Blitz3D) always facing the camera (top view) ✔
![image](https://user-images.githubusercontent.com/57479219/234816848-b2a643bf-8eef-4247-a52f-00ab97b45b1c.png)

Mode3 (OpenB3D) seeing the top view (should always face the camera, but roll with it) ❌
![image](https://user-images.githubusercontent.com/57479219/234817368-e06008bb-ac7c-47c9-9c21-6bc220c32f2e.png)

Mode 4 (Blitz3D) seeing the top view: ✔
![image](https://user-images.githubusercontent.com/57479219/234813099-d3185e1f-68fe-4990-bb4d-2080bd39c190.png)

Mode 4 (OpenB3D) spinning and then vanishes when pitch reaches the top view: ❌
![image](https://user-images.githubusercontent.com/57479219/234813400-3bc03529-374b-4a87-a0ca-eb7b5c7622b8.png)

**Comment by angros47** [comment]
Can you show me a code example? I can't reproduce your issue

**Comment by blitzcoder** [comment]
Sure, here's the OpenB3D BlitzMax version, ported from [Blitz3D Example](https://github.com/blitz-research/blitz3d/blob/master/_release/help/commands/3d_examples/SpriteViewMode.bb)

```
' SpriteViewMode Example
' ----------------------

'Strict

Framework Openb3d.B3dglgraphics

Graphics3D 640,480,0,2

Local pivot:TEntity=CreatePivot()
PositionEntity pivot,0,1,0

Local camera:TCamera=CreateCamera(pivot)
PositionEntity camera,0,0,10

Local light:TLight=CreateLight()
RotateEntity light,90,0,0

Local plane:TMesh=CreatePlane()
Local ground_tex:TTexture=LoadTexture("media/Chorme-2.bmp")
EntityTexture plane,ground_tex

Local sprite:TSprite=LoadSprite("media/b3dlogo.jpg")
PositionEntity sprite,0,1,0

Local pitch#=-15
Local yaw#=180
Local roll#=0
Local view_mode%=1
Local view_mode_info$=" (fixed)"

While Not KeyDown(KEY_ESCAPE)

If KeyDown(KEY_DOWN)=True And pitch<0 Then pitch=pitch+1
If KeyDown(KEY_UP)=True And pitch>-89 Then pitch=pitch-1
If KeyDown(KEY_RIGHT)=True Then yaw=yaw+1
If KeyDown(KEY_LEFT)=True Then yaw=yaw-1
If KeyDown(KEY_A)=True Then roll=roll+1
If KeyDown(KEY_S)=True Then roll=roll-1

' Change sprite view mode depending on key pressed
If KeyHit(KEY_1)=True Then view_mode=1 ; view_mode_info$=" (fixed)"
If KeyHit(KEY_2)=True Then view_mode=2 ; view_mode_info$=" (free)"
If KeyHit(KEY_3)=True Then view_mode=3 ; view_mode_info$=" (upright1)"
If KeyHit(KEY_4)=True Then view_mode=4 ; view_mode_info$=" (upright2)"

' Set sprite view mode
SpriteViewMode sprite,view_mode

RotateEntity pivot,pitch,yaw,0
PointEntity camera,sprite,roll

RenderWorld

Text 0,0,"Use cursor keys to orbit camera around sprite"
Text 0,20,"Press A and S keys to roll camera"
Text 0,40,"Press keys 1-4 to change sprite view mode"
Text 0,60,"SpriteViewMode: "+view_mode+view_mode_info$

Flip

Wend

End
```

**Comment by blitzcoder** [comment]
To follow, just putting the camera overhead or on top of the sprite in modes 3 and 4 will trigger the issue.

**Comment by angros47** [comment]
I have the impression the issue happens only if the camera is a child of "pivot". If the camera has no parent, everything works right.

I think the issue is that EntityPitch and EntityYaw don't work correctly with global argument

**Comment by angros47** [comment]
I might have found the cause, but I need a little test from you

After the line:
Local pivot:TEntity=CreatePivot()

add the line:
EntityParent pivot,0

Does it change anything?

**Comment by angros47** [comment]
If my previous test works, the bug can be fixed by removing all the occurrences of the line:

if(parent_ent==NULL) parent_ent=Global::root_ent;

in pivot.cpp

**Comment by blitzcoder** [comment]
Yes, adding that line seems to be working now as intended. 

Noted on the updated fix, closing.
